SERVER:
  INSTANCE_CONNECTION_NAME:
  NAME: template-wire
  ENV: dev
  HOST:
  PORT: 5555
  CONFIG_FILE:
  TZ: Asia/Ho_Chi_Minh

MYSQL:
  DB_USERNAME:
  DB_PASSWORD:
  DB_HOST: 10.21.0.3
  DB_PORT: 3306
  DB_NAME: promotion
  DB_SOCKET_DIR:
  DB_CONN_MAX_LIFETIME:
  DB_MAX_IDLE_CONNS:
  DB_MAX_OPEN_CONNS:

GCP:
  PROJECT_ID: dev

PUBSUB_TOPIC:
  NOTIFICATION_TOPIC:

API_KEY:
  NOTIFICATION_API_KEY:
  PROMOTION_API_KEY:
  PORTFOLIO_API_KEY:
  STOCK_ORDER_API_KEY:
