SERVER:
  INSTANCE_CONNECTION_NAME:
  NAME: promotion
  ENV: dev
  HOST:
  PORT:
  CONFIG_FILE:
  TZ:

MYSQL:
  DB_USERNAME:
  DB_PASSWORD:
  DB_HOST:
  DB_PORT:
  DB_NAME:
  DB_SOCKET_DIR:
  DB_CONN_MAX_LIFETIME:
  DB_MAX_IDLE_CONNS:
  DB_MAX_OPEN_CONNS:

GCP:
  PROJECT_ID:

PUBSUB_TOPIC:
  NOTIFICATION_TOPIC:

API_KEY:
  NOTIFICATION_API_KEY:
  PROMOTION_API_KEY:
  PORTFOLIO_API_KEY:
  STOCK_ORDER_API_KEY:
